// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using visual_studio_code_courses_authors.Data;

namespace visualstudiocodecoursesauthors.Migrations.AuthorDb
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20180210091806_changeAuthorCreatedDate")]
    partial class changeAuthorCreatedDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("visual_studio_code_courses_authors.Models.Course.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
